name = "danogo-io/predict-interest-rate"
version = "0.0.0"
compiler = "v1.1.4"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'danogo-io/predict-interest-rate'"

[repository]
user = "danogo-io"
project = "predict-interest-rate"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[[dependencies]]
name = "danogo2023/daken"
version = "v2.0.0"
source = "github"

[config]
